<?php
namespace AlAdhanApi;

class Methods {
    
    const SIA = 0; // SHIA ITHNA-ASHARI
    const UoISK = 1; //UNIVERSITY OF ISLAMIC SCIENCES, KARACHI
    const ISoNA = 2; //ISLAMIC SOCIETY OF NORTH AMERICA
    const MWL = 3; // MUSLIM WORLD LEGUE
    const MAKKAH = 4; // UMM AL-QURA, MAKKAH
    const EGAoS = 5; // EGYPTIAN GENERAL AUTHORITY OF SURVEY
    const IoGUoT = 7; // INSTITUTE OF GEOPHYSICS, UNIVERSITY OF TEHRAN
}